name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Kalkulator.java
        run: javac src/Kalkulator.java

      - name: Make test script executable
        run: chmod +x src/test_add.sh

      - name: Run test
        run: java -cp . Kalkulator add 2 3

