name: CI Pipeline

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3
    with:
      java-version: '17'
      distribution: 'temurin'

    - name: Compile Kalkulator.java
      run: javac Kalkulator.java

    - name: Run test
      run: ./test_add.sh
